"""Initial Migration

Revision ID: 04540c2575f8
Revises: 
Create Date: 2024-09-01 09:24:38.650168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04540c2575f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_content', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_event_id'), 'system_event', ['id'], unique=False)
    op.create_table('subsystem_event',
    sa.Column('system_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_content', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['system_event_id'], ['system_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsystem_event_id'), 'subsystem_event', ['id'], unique=False)
    op.create_table('system_feedback',
    sa.Column('system_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['system_event_id'], ['system_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_feedback_id'), 'system_feedback', ['id'], unique=False)
    op.create_table('system_input',
    sa.Column('system_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['system_event_id'], ['system_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_input_id'), 'system_input', ['id'], unique=False)
    op.create_table('system_metadata',
    sa.Column('system_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['system_event_id'], ['system_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metadata_id'), 'system_metadata', ['id'], unique=False)
    op.create_table('system_output',
    sa.Column('system_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['system_event_id'], ['system_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_output_id'), 'system_output', ['id'], unique=False)
    op.create_table('component_event',
    sa.Column('subsystem_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_content', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['subsystem_event_id'], ['subsystem_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_event_id'), 'component_event', ['id'], unique=False)
    op.create_table('subsystem_feedback',
    sa.Column('subsystem_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['subsystem_event_id'], ['subsystem_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsystem_feedback_id'), 'subsystem_feedback', ['id'], unique=False)
    op.create_table('subsystem_input',
    sa.Column('subsystem_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['subsystem_event_id'], ['subsystem_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsystem_input_id'), 'subsystem_input', ['id'], unique=False)
    op.create_table('subsystem_metadata',
    sa.Column('subsystem_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subsystem_event_id'], ['subsystem_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsystem_metadata_id'), 'subsystem_metadata', ['id'], unique=False)
    op.create_table('subsystem_output',
    sa.Column('subsystem_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['subsystem_event_id'], ['subsystem_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsystem_output_id'), 'subsystem_output', ['id'], unique=False)
    op.create_table('component_feedback',
    sa.Column('component_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['component_event_id'], ['component_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_feedback_id'), 'component_feedback', ['id'], unique=False)
    op.create_table('component_input',
    sa.Column('component_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['component_event_id'], ['component_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_input_id'), 'component_input', ['id'], unique=False)
    op.create_table('component_metadata',
    sa.Column('component_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['component_event_id'], ['component_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_metadata_id'), 'component_metadata', ['id'], unique=False)
    op.create_table('component_output',
    sa.Column('component_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['component_event_id'], ['component_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_output_id'), 'component_output', ['id'], unique=False)
    op.create_table('subcomponent_event',
    sa.Column('component_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_content', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['component_event_id'], ['component_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcomponent_event_id'), 'subcomponent_event', ['id'], unique=False)
    op.create_table('subcomponent_feedback',
    sa.Column('subcomponent_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['subcomponent_event_id'], ['subcomponent_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcomponent_feedback_id'), 'subcomponent_feedback', ['id'], unique=False)
    op.create_table('subcomponent_input',
    sa.Column('subcomponent_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['subcomponent_event_id'], ['subcomponent_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcomponent_input_id'), 'subcomponent_input', ['id'], unique=False)
    op.create_table('subcomponent_metadata',
    sa.Column('subcomponent_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['subcomponent_event_id'], ['subcomponent_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcomponent_metadata_id'), 'subcomponent_metadata', ['id'], unique=False)
    op.create_table('subcomponent_output',
    sa.Column('subcomponent_event_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['subcomponent_event_id'], ['subcomponent_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcomponent_output_id'), 'subcomponent_output', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcomponent_output_id'), table_name='subcomponent_output')
    op.drop_table('subcomponent_output')
    op.drop_index(op.f('ix_subcomponent_metadata_id'), table_name='subcomponent_metadata')
    op.drop_table('subcomponent_metadata')
    op.drop_index(op.f('ix_subcomponent_input_id'), table_name='subcomponent_input')
    op.drop_table('subcomponent_input')
    op.drop_index(op.f('ix_subcomponent_feedback_id'), table_name='subcomponent_feedback')
    op.drop_table('subcomponent_feedback')
    op.drop_index(op.f('ix_subcomponent_event_id'), table_name='subcomponent_event')
    op.drop_table('subcomponent_event')
    op.drop_index(op.f('ix_component_output_id'), table_name='component_output')
    op.drop_table('component_output')
    op.drop_index(op.f('ix_component_metadata_id'), table_name='component_metadata')
    op.drop_table('component_metadata')
    op.drop_index(op.f('ix_component_input_id'), table_name='component_input')
    op.drop_table('component_input')
    op.drop_index(op.f('ix_component_feedback_id'), table_name='component_feedback')
    op.drop_table('component_feedback')
    op.drop_index(op.f('ix_subsystem_output_id'), table_name='subsystem_output')
    op.drop_table('subsystem_output')
    op.drop_index(op.f('ix_subsystem_metadata_id'), table_name='subsystem_metadata')
    op.drop_table('subsystem_metadata')
    op.drop_index(op.f('ix_subsystem_input_id'), table_name='subsystem_input')
    op.drop_table('subsystem_input')
    op.drop_index(op.f('ix_subsystem_feedback_id'), table_name='subsystem_feedback')
    op.drop_table('subsystem_feedback')
    op.drop_index(op.f('ix_component_event_id'), table_name='component_event')
    op.drop_table('component_event')
    op.drop_index(op.f('ix_system_output_id'), table_name='system_output')
    op.drop_table('system_output')
    op.drop_index(op.f('ix_system_metadata_id'), table_name='system_metadata')
    op.drop_table('system_metadata')
    op.drop_index(op.f('ix_system_input_id'), table_name='system_input')
    op.drop_table('system_input')
    op.drop_index(op.f('ix_system_feedback_id'), table_name='system_feedback')
    op.drop_table('system_feedback')
    op.drop_index(op.f('ix_subsystem_event_id'), table_name='subsystem_event')
    op.drop_table('subsystem_event')
    op.drop_index(op.f('ix_system_event_id'), table_name='system_event')
    op.drop_table('system_event')
    # ### end Alembic commands ###
