query UserWorkspaces($workspaceId: Uuid, $workspaceName: String, $userId: Uuid, $username: String) {
  workspace(id: $workspaceId, name: $workspaceName) {
    users {
      role
      user(id: $userId, username: $username) {
        id
        username
        displayName
        status
        isAdmin
        isSysadmin
      }
    }
  }
}
