query UserWorkspaces($Id: Uuid) {
  workspace(id: $Id) {
    users {
      role
      user {
        id
        username
        displayName
        status
        isAdmin
        isSysadmin
      }
    }
  }
}
