services:
  api:
    container_name: api
    build:
      dockerfile: api/Dockerfile
    env_file:
      - .env
    ports:
      - "8684:8000"
      - "50051:50051"
    volumes:
      - ./api:/app
    networks:
      - ptolemy
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - ptolemy
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - ptolemy
    volumes:
      - clickhouse:/var/lib/clickhouse
      - ./clickhouse/config.d:/etc/clickhouse-server/config.d
  goose:
    container_name: goose
    build:
      context: ./goose
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./goose:/app
    networks:
      - ptolemy
    depends_on:
      - clickhouse
    profiles: ["dev"]

volumes:
  postgres:
    driver: local
  clickhouse:
    driver: local

networks:
  ptolemy:
    driver: bridge
