services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8684:8684"
    volumes:
      - ./api:/app
    networks:
      - ptolemy
    depends_on:
      - postgres
      - redis
  observer:
    container_name: observer
    build:
      context: ./observer
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./observer:/app
      - ./proto:/app/proto
    networks:
      - ptolemy
    ports:
      - "50051:50051"
    depends_on:
      - redis
  postgres:
    container_name: postgres
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - ptolemy
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - ptolemy
    volumes:
      - redis:/data
  redisinsight:
    container_name: redisinsight
    image: redis/redisinsight
    ports:
      - "5540:5540"
    networks:
      - ptolemy
    volumes:
      - redisinsight:/data
    profiles: ["dev"]
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - ptolemy
    volumes:
      - clickhouse:/var/lib/clickhouse
  goose:
    container_name: goose
    build:
      context: ./goose
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./goose:/app
    networks:
      - ptolemy
    depends_on:
      - clickhouse
    profiles: ["dev"]

volumes:
  postgres:
    driver: local
  clickhouse:
    driver: local
  redis:
    driver: local
  redisinsight:
    driver: local

networks:
  ptolemy:
    driver: bridge
