services:
  ptolemy:
    build:
      context: ./ptolemy
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./ptolemy:/app
    networks:
      - ptolemy
    depends_on:
      - postgres
  observer:
    build:
      context: ./observer
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./observer:/app
      - ./proto:/app/proto
    networks:
      - ptolemy
    ports:
      - "50051:50051"
    depends_on:
      - redis
  ptolemy_test:
    build:
      context: ./ptolemy
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - ./ptolemy:/app
    networks:
      - ptolemy
    depends_on:
      - postgres
      - ptolemy
    command: python3 -m pytest . --force-sugar -vvv --cov=ptolemy --cov-report=html --profile
  postgres:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - ptolemy
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - ptolemy

volumes:
  postgres:
    driver: local

networks:
  ptolemy:
    driver: bridge
