services:
  api:
    container_name: api
    build:
      dockerfile: api/Dockerfile
    environment:
      # disable if the debug logs get too annoying
      RUST_LOG: info,api=debug,ptolemy=debug
    ports:
      - "7865:7865"
      - "50051:50051"
    volumes:
      - ./api:/app
      - ptolemy_data:/ptolemy/data
    networks:
      - ptolemy

volumes:
  ptolemy_data:
    driver: local

networks:
  ptolemy:
    driver: bridge
