services:
  ptolemy:
    build:
      context: ./ptolemy
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./ptolemy:/app
    networks:
      - ptolemy
    depends_on:
      - postgres
      - redis
  app:
    build:
      context: ./ptolemy
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./ptolemy:/app
    networks:
      - ptolemy
    depends_on:
      - ptolemy
    command: python3 -m streamlit run streamlit_app.py
  observer:
    build:
      context: ./observer
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./observer:/app
      - ./proto:/app/proto
    networks:
      - ptolemy
    ports:
      - "50051:50051"
    depends_on:
      - redis
  postgres:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - ptolemy
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - ptolemy
    volumes:
      - redis:/data
  redisinsight:
    image: redis/redisinsight
    ports:
      - "5540:5540"
    networks:
      - ptolemy
    volumes:
      - redisinsight:/data
  vector:
    image: timberio/vector:0.43.0-alpine
    ports:
      - "8686:8686"
    networks:
      - ptolemy
    env_file:
      - .env
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml:ro
      - ./vector/observer.desc:/etc/vector/observer.desc:ro
    depends_on:
      - observer
      - clickhouse
      - redis
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
    networks:
      - ptolemy
    volumes:
      - clickhouse:/var/lib/clickhouse

volumes:
  postgres:
    driver: local
  clickhouse:
    driver: local
  redis:
    driver: local
  redisinsight:
    driver: local

networks:
  ptolemy:
    driver: bridge
