services:
  api:
    container_name: api
    build:
      dockerfile: api/Dockerfile
    env_file:
      - .env
    ports:
      - "8684:8000"
      - "50051:50051"
    volumes:
      - ./api:/app
    networks:
      - ptolemy
    depends_on:
      - postgres
      - clickhouse
  postgres:
    container_name: postgres
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - ptolemy

volumes:
  postgres:
    driver: local

networks:
  ptolemy:
    driver: bridge
