services:
  api:
    container_name: api
    build:
      dockerfile: api/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ptolemy
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      # disable if the debug logs get too annoying
      RUST_LOG: info,api=debug,ptolemy=debug
      # set to "PROD" for production
      PTOLEMY_ENV: DEV
      # JWT secret goes here
      JWT_SECRET: pC15dRLduel2TYONYEfyjHZ289j7dIXv1RXL09T/t0o=
    ports:
      - "8000:8000"
      - "50051:50051"
    volumes:
      - ./api:/app
      - ptolemy_data:/ptolemy/data
    networks:
      - ptolemy
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ptolemy
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - ptolemy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  app:
    container_name: app
    build:
      dockerfile: prototype/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./prototype:/app/prototype
    networks:
      - ptolemy

volumes:
  postgres:
    driver: local
  grafana_data:
    driver: local
  ptolemy_data:
    driver: local

networks:
  ptolemy:
    driver: bridge
