global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ptolemy'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
