[tool.poetry]
name = "tvali"
version = "0.0.1"
description = "An open-source ML monitoring platform built for complex systems."
authors = ["Raz Besaleli <rbesaleli@gmail.com>"]
readme = "README.md"
[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["standard"], version = "^0.112.2", optional = true}
uvicorn = {extras = ["standard"], version = "^0.30.6", optional = true}
sqlalchemy = {version = "^2.0.32", optional = true}
python-dotenv = "^1.0.1"
pydantic = "^2.8.2"
requests = "^2.32.3"
psycopg = {extras = ["binary"], version = "^3.2.1", optional = true}
alembic = {version = "^1.13.2", optional = true}
[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"

pytest-cov = "^5.0.0"
pytest-sugar = "^1.0.0"
pytest-asyncio = "^0.24.0"
pylint = "^3.2.7"
black = "^24.8.0"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
[tool.poetry.extras]
api = ["fastapi", "uvicorn", "sqlalchemy", "psycopg", "alembic"]

[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'
