[project]
name = "query-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.1.3",
    "fastapi[standard]>=0.115.8",
    "polars>=1.21.0",
    "pyarrow>=18.1.0",
    "uvicorn[standard]>=0.34.0",
]
