query UserWorkspaces($Id: Uuid, $username: String) {
  user(id: $Id, username: $username) {
    workspaces {
      archived
      description
      id
      name
      createdAt
      updatedAt
      users(username: $username) {
        role
      }
    }
  }
}
