mutation CreateUserApiKey($name: String!, $userId: Uuid!, $durationDays: Int) {
  createUserApiKey(name: $name, userId: $userId, durationDays: $durationDays) {
    apiKey {
      apiKey
    }
    error {
      field
      message
    }
    success
  }
}