mutation AddUserToWorkspace($userId: Uuid!, $targetUserId: Uuid!, $workspaceId: Uuid!, $role: WorkspaceRoleEnum!) {
  workspace(userId: $userId) {
    addUser(
      workspaceUser: {userId: $targetUserId, workspaceId: $workspaceId, role: $role}
    ) {
      success
      error {
        field
        message
      }
    }
  }
}