mutation DeleteUserFromWorkspace($targetUserId: Uuid!, $userId: Uuid!, $workspaceId: Uuid!) {
  deleteUserFromWorkspace(targetUserId: $targetUserId, userId: $userId, workspaceId: $workspaceId) {
    error {
      field
      message
    }
    success
  }
}