# Generated by Django 5.1 on 2024-08-31 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('parameters', models.JSONField()),
                ('error_type', models.CharField(max_length=128)),
                ('error_content', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubsystemEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('parameters', models.JSONField()),
                ('error_type', models.CharField(max_length=128)),
                ('error_content', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('parameters', models.JSONField()),
                ('error_type', models.CharField(max_length=128)),
                ('error_content', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentFeedback',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=128)),
                ('field_value', models.JSONField()),
                ('component_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.componentevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentInput',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=128)),
                ('field_value', models.JSONField()),
                ('component_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.componentevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentMetadata',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=128)),
                ('field_value', models.CharField(max_length=256)),
                ('component_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.componentevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentOutput',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=128)),
                ('field_value', models.JSONField()),
                ('component_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.componentevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubcomponentEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('parameters', models.JSONField()),
                ('error_type', models.CharField(max_length=128)),
                ('error_content', models.JSONField()),
                ('component_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.componentevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubcomponentFeedback',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=128)),
                ('field_value', models.JSONField()),
                ('subcomponent_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subcomponentevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubcomponentInput',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=128)),
                ('field_value', models.JSONField()),
                ('subcomponent_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subcomponentevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubcomponentMetadata',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=128)),
                ('field_value', models.CharField(max_length=256)),
                ('subcomponent_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subcomponentevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubcomponentOutput',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=128)),
                ('field_value', models.JSONField()),
                ('subcomponent_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subcomponentevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='componentevent',
            name='subsystem_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subsystemevent'),
        ),
        migrations.CreateModel(
            name='SubsystemFeedback',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=128)),
                ('field_value', models.JSONField()),
                ('subsystem_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subsystemevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubsystemInput',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=128)),
                ('field_value', models.JSONField()),
                ('subsystem_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subsystemevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubsystemMetadata',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=128)),
                ('field_value', models.CharField(max_length=256)),
                ('subsystem_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subsystemevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubsystemOutput',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=128)),
                ('field_value', models.JSONField()),
                ('subsystem_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subsystemevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subsystemevent',
            name='system_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.systemevent'),
        ),
    ]
