[env]
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "postgres"
POSTGRES_HOST = "localhost"
POSTGRES_DB = "ptolemy"
POSTGRES_PORT = "5432"

PTOLEMY_ENV = "DEV"
JWT_SECRET = "pC15dRLduel2TYONYEfyjHZ289j7dIXv1RXL09T/t0o="
RUST_LOG = "info,api=debug,ptolemy=debug"

API_PORT = "8000"
PTOLEMY_USER = "admin"
PTOLEMY_PASS = "admin"

REDIS_HOST= "localhost"
REDIS_PORT= "6379"
REDIS_DB= "0"
