mutation CreateUserApiKey($name: String!, $userId: Uuid!, $durationDays: Int) {
  user(userId: $userId) {
    createUserApiKey(name: $name, durationDays: $durationDays) {
      apiKey {
        apiKey
      }
      error {
        field
        message
      }
      success
    }
  }
}

mutation CreateUser($userId: Uuid!, $username: String!, $password: String!, $isAdmin: Boolean!, $displayName: String) {
  user(userId: $userId) {
    create(
      userData: {username: $username, password: $password, isSysadmin: false, isAdmin: $isAdmin, displayName: $displayName}
    ) {
      error {
        field
        message
      }
      success
      user {
        displayName
        id
        isAdmin
        isSysadmin
        status
        username
      }
    }
  }
}

mutation DeleteUserApiKey($apiKeyId: Uuid!, $userId: Uuid!) {
  user(userId: $userId) {
    deleteUserApiKey(apiKeyId: $apiKeyId) {
      error {
        field
        message
      }
      success
    }
  }
}

mutation DeleteUser($Id: Uuid!, $userId: Uuid!) {
  user(userId: $userId) {
    delete(id: $Id) {
      error {
        field
        message
      }
      success
    }
  }
}

mutation AddUserToWorkspace($userId: Uuid!, $targetUserId: Uuid!, $workspaceId: Uuid!, $role: WorkspaceRoleEnum!) {
  workspace(userId: $userId) {
    addUser(
      workspaceUser: {userId: $targetUserId, workspaceId: $workspaceId, role: $role}
    ) {
      success
      error {
        field
        message
      }
    }
  }
}

mutation ChangeWorkspaceUserRole($role: WorkspaceRoleEnum!, $targetUserId: Uuid!, $userId: Uuid!, $workspaceId: Uuid!) {
  workspace(userId: $userId) {
    changeWorkspaceUserRole(
      newRole: $role
      userId: $targetUserId
      workspaceId: $workspaceId
    ) {
      error {
        field
        message
      }
      success
    }
  }
}

mutation CreateServiceApiKey($name: String!, $permission: ApiKeyPermissionEnum!, $userId: Uuid!, $workspaceId: Uuid!, $durationDays: Int) {
  workspace(userId: $userId) {
    createServiceApiKey(
      name: $name
      permission: $permission
      workspaceId: $workspaceId
      durationDays: $durationDays
    ) {
      error {
        field
        message
      }
      success
      apiKey {
        apiKey
      }
    }
  }
}

mutation DeleteServiceApiKey($apiKeyId: Uuid!, $userId: Uuid!, $workspaceId: Uuid!) {
  workspace(userId: $userId) {
    deleteServiceApiKey(apiKeyId: $apiKeyId, workspaceId: $workspaceId) {
      success
      error {
        field
        message
      }
    }
  }
}

mutation CreateWorkspace($userId: Uuid!, $name: String!, $description: String, $adminUserId: Uuid!) {
  workspace(userId: $userId) {
    create(
      workspaceData: {name: $name, description: $description}
      adminUserId: $adminUserId
    ) {
      error {
        field
        message
      }
      workspace {
        id
        name
        description
        archived
        createdAt
        updatedAt
      }
    }
  }
}

mutation RemoveUserFromWorkspace($targetUserId: Uuid!, $userId: Uuid!, $workspaceId: Uuid!) {
  workspace(userId: $userId) {
    removeUser(userId: $targetUserId, workspaceId: $workspaceId) {
      error {
        field
        message
      }
      success
    }
  }
}

mutation DeleteWorkspace($userId: Uuid!, $workspaceId: Uuid!) {
  workspace(userId: $userId) {
    delete(workspaceId: $workspaceId) {
      success
      error {
        field
        message
      }
    }
  }
}

mutation Login($username: String!, $password: String!) {
  auth(userData: {username: $username, password: $password}) {
    error {
      field
      message
    }
    success
    token
    user {
      displayName
      id
      isAdmin
      isSysadmin
      status
      username
    }
  }
}
