mutation CreateUserApiKey($name: String!, $durationDays: Int) {
  user {
    createUserApiKey(name: $name, durationDays: $durationDays) {
      apiKey {
        apiKey
      }
      ...Result
    }
  }
}

mutation CreateUser($username: String!, $password: String!, $isAdmin: Boolean!, $displayName: String) {
  user {
    create(
      userData: {username: $username, password: $password, isSysadmin: false, isAdmin: $isAdmin, displayName: $displayName}
    ) {
      ...Result
      user {
        ...ReturnsUser
      }
    }
  }
}

mutation DeleteUserApiKey($apiKeyId: UUID!) {
  user {
    deleteUserApiKey(apiKeyId: $apiKeyId) {
      ...Result
    }
  }
}

mutation DeleteUser($userId: UUID!) {
  user {
    delete(id: $userId) {
      ...Result
    }
  }
}

mutation AddUserToWorkspace($userId: UUID!, $workspaceId: UUID!, $role: WorkspaceRoleEnum!) {
  workspace {
    addUser(
      workspaceUser: {userId: $userId, workspaceId: $workspaceId, role: $role}
    ) {
      ...Result
    }
  }
}

mutation ChangeWorkspaceUserRole($role: WorkspaceRoleEnum!, $userId: UUID!, $workspaceId: UUID!) {
  workspace {
    changeWorkspaceUserRole(
      newRole: $role
      userId: $userId
      workspaceId: $workspaceId
    ) {
      ...Result
    }
  }
}

mutation CreateServiceApiKey($name: String!, $permission: ApiKeyPermissionEnum!, $workspaceId: UUID!, $durationDays: Int) {
  workspace {
    createServiceApiKey(
      name: $name
      permission: $permission
      workspaceId: $workspaceId
      durationDays: $durationDays
    ) {
      ...Result
      apiKey {
        apiKey
      }
    }
  }
}

mutation DeleteServiceApiKey($apiKeyId: UUID!, $workspaceId: UUID!) {
  workspace {
    deleteServiceApiKey(apiKeyId: $apiKeyId, workspaceId: $workspaceId) {
      ...Result
    }
  }
}

mutation CreateWorkspace($name: String!, $description: String, $adminUserId: UUID!) {
  workspace {
    create(
      workspaceData: {name: $name, description: $description}
      adminUserId: $adminUserId
    ) {
      ...Result
      workspace {
        ...ReturnsWorkspace
      }
    }
  }
}

mutation RemoveUserFromWorkspace($userId: UUID!, $workspaceId: UUID!) {
  workspace {
    removeUser(userId: $userId, workspaceId: $workspaceId) {
      ...Result
    }
  }
}

mutation DeleteWorkspace($workspaceId: UUID!) {
  workspace {
    delete(workspaceId: $workspaceId) {
      ...Result
    }
  }
}

fragment ReturnsUser on User {
  displayName
  id
  isAdmin
  isSysadmin
  status
  username
}

fragment Result on GQLResult {
  error {
    field
    message
  }
  success
}

fragment ReturnsWorkspace on Workspace {
  id
  name
  description
  archived
  createdAt
  updatedAt
}
