[package]
name = "ptolemy"
version = "0.1.0"
edition = "2021"

[lib]
name = "_core"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
# "abi3-py39" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.9
pyo3 = { version = "0.23.3", features = ["extension-module", "abi3-py311", "chrono"] }
tonic = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
tonic-types = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
serde_repr = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }
ptolemy-core = { path = "../ptolemy-core" }
chrono = { workspace = true }
heck = "0.5.0"
once_cell = "1.20.2"

[dependencies.pyo3-ffi]
version = "0.23.3"
features = ["extension-module", "abi3"]

[build-dependencies]
tonic-build = "0.12.3"
