[package]
name = "ptolemy"
version = "0.1.0"
edition = "2021"

[lib]
name = "_core"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
# "abi3-py39" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.9
pyo3 = { version = "0.22.4", features = ["extension-module", "abi3-py39"] }
tonic = "0.12.3"
prost = "*"
tokio = { version = "1.41.1", features = ["full"] }
log = "0.4.22"
env_logger = "0.11.5"
tonic-types = "0.12.3"
prost-types = "0.13.4"
clickhouse = { version = "0.13.1", features = ["uuid", "time"] }
serde = {version = "1.0.216", features = ["derive"] }
serde_repr = "0.1.19"
uuid = "1.11.0"
serde_json = "1.0.133"

[build-dependencies]
tonic-build = "0.12.3"
