[project]
name = "ptolemy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Raz Besaleli", email = "rbesaleli@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.10",
    "clickhouse-connect>=0.8.9",
    "grpcio-tools>=1.68.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
