query UserWorkspaces($Id: Uuid) {
  user(id: $Id) {
    workspaces {
      archived
      description
      id
      name
      createdAt
      updatedAt
      users(id: $Id) {
        role
      }
    }
  }
}
