query UserWorkspacesByUsername($username: String!) {
  user(username: $username) {
    workspaces {
      archived
      description
      id
      name
      createdAt
      updatedAt
      users(username: $username) {
        role
      }
    }
  }
}
