site_name: "Ptolemy"
site_url: http://docs.ptolemy.dev

theme:
  name: material
  logo: img/logomark-white.svg
  favicon: img/favicon.ico
  palette:
    scheme: slate
    primary: custom
    accent: custom
  font:
    text: B612
    code: B612 Mono
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.instant
    - search.suggest
    - navigation.tabs
    # - navigation.tabs.sticky
    - content.code.copy

repo_name: PtolemyLovesYou/ptolemy
repo_url: https://github.com/PtolemyLovesYou/ptolemy
edit_uri: edit/main/docs/

nav:
  - Home:
    - index.md
  - Getting Started:
    - Introduction: getting_started/index.md
    - Install with Docker Compose: getting_started/installation_docker_compose.md
    - Configuration: getting_started/configuration.md
    - Building Documentation: getting_started/building_documentation.md
    - Usage: getting_started/usage.md
  - Concepts:
    - Introduction: concepts/introduction.md
    - Identity & Access Management: concepts/iam.md
  - Guides:
    - Introduction: guides/index.md
  - API Reference:
    - Introduction: api_reference/introduction.md
    - GraphQL Schema: api_reference/gql_schema.md
    - System Diagrams:
      - Database Schema: api_reference/system_diagrams/database_schema.md
      - Query Engine Service Architecture: api_reference/system_diagrams/query_engine.md
  - Integrations:
    - integrations.md
  - Contributing:
    - Introduction: contributing/index.md
    - Code of Conduct: contributing/code_of_conduct.md
    - Core Maintainers: contributing/core_maintainers.md

plugins:
  - search
  - plantuml:
        puml_url: https://www.plantuml.com/plantuml/
        verbose: true
        theme:
          dark: material/light-green-dark

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path: ['.', '../api', '../ptolemy']

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
extra_css:
  - stylesheets/extra.css
