[project]
name = "docs"
version = "0.1.0-alpha.5+15116f7"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [ "mkdocs-puml>=2.3.0", "mkdocs>=1.6.1", "mkdocs-material[imaging]>=9.5.48", "mkdocs-table-reader-plugin>=3.1.0",]
