mutation MyMutation($userId: Uuid!, $name: String!, $description: String, $adminUserId: Uuid!) {
  createWorkspace(
    userId: $userId
    workspaceData: {name: $name, description: $description}
    adminUserId: $adminUserId
  ) {
    error {
      field
      message
    }
    workspace {
      id
      name
      description
      archived
    }
  }
}