# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema.auth]
file = "src/generated/auth_schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
filter = { only_tables = ["workspace", "users", "workspace_user", "user_api_key", "service_api_key"] }

[print_schema.records]
file = "src/generated/records_schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
filter = { only_tables = ["workspace", "system_event", "subsystem_event", "component_event", "subcomponent_event", "runtime", "io", "metadata"] }

[print_schema.audit]
file = "src/generated/audit_schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
filter = { only_tables = ["api_auth_audit_logs", "api_access_audit_logs", "iam_audit_logs", "record_audit_logs"] }
[migrations_directory]
dir = "/app/diesel"
