# .github/workflows/coverage.yml
name: Test and Upload Coverage

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: |
          pip install uv
      - name: Sync
        run: |
          uv sync --locked --all-packages --dev

      - name: Run tests with coverage
        run: |
          uv run -m coverage run -m pytest ptolemy-py
          uv run -m coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
